Update send_quote.yml

diff --git a/.github/workflows/send_quote.yml b/.github/workflows/send_quote.yml
--- a/.github/workflows/send_quote.yml
+++ b/.github/workflows/send_quote.yml
@@ -10,35 +10,37 @@ jobs:
         with:
           node-version: 14
       - uses: actions/checkout@v3
-      - run: |
-          if echo "${{ secrets.airtable_token }}" != ""; then
-            quotes=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/Phrases?maxRecords=3&view=Grid%20view" \
-            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
-          else
-            echo "::warning::No Airtable token found!"
-            exit 1
-          fi
-          if echo "${{ secrets.airtable_token }}" != ""; then
-            phone_numbers=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/tbllxCDF1n7n83XDB?fields%5B%5D=number" \
-            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
-          else
-            echo "::warning::No Airtable token found!"
-            exit 1
-          fi
-          if ! payload=$(npm run format "${quotes}" "${phone_numbers}"); then
-            echo "::warning::Failed to map data to JSON!"
-            exit 1
-          fi
-          if echo "${{ secrets.twilio_sid }} == ""; then
-            echo "::warning::No Twilio SID found!"
-            exit 1
-          fi
-          if echo "${{ secrets.twilio_auth_token }} == ""; then
-            echo "::warning::No Twilio Auth Token found!"
-            exit 1
-          fi
-          curl -X POST "https://studio.twilio.com/v2/Flows/FWff44ff6e975387006dc5bdb613757961/Executions" \
-          --data-urlencode "To=${{ secrets.twilio_number }} \
-          --data-urlencode "From=${{ secrets.proxy_number }} \
-          -u "${{ secrets.twilio_sid }}:${{ secrets.twilio_auth_token }}" \
-          -d "${payload}"
+      - env:
+          twilio_auth_token: ${{ secrets.twilio_auth_token }}
+          run: |
+            if echo "${{ secrets.airtable_token }}" != ""; then
+              quotes=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/Phrases?maxRecords=3&view=Grid%20view" \
+              -H "Authorization: Bearer ${{ secrets.airtable_token }}")
+            else
+              echo "::warning::No Airtable token found!"
+              exit 1
+            fi
+            if echo "${{ secrets.airtable_token }}" != ""; then
+              phone_numbers=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/tbllxCDF1n7n83XDB?fields%5B%5D=number" \
+              -H "Authorization: Bearer ${{ secrets.airtable_token }}")
+            else
+              echo "::warning::No Airtable token found!"
+              exit 1
+            fi
+            if ! payload=$(npm run format "${quotes}" "${phone_numbers}"); then
+              echo "::warning::Failed to map data to JSON!"
+              exit 1
+            fi
+            if echo "${{ secrets.twilio_sid }} == ""; then
+              echo "::warning::No Twilio SID found!"
+              exit 1
+            fi
+            if echo "${{ env.twilio_auth_token }} == ""; then
+              echo "::warning::No Twilio Auth Token found!"
+              exit 1
+            fi
+            curl -X POST "https://studio.twilio.com/v2/Flows/FWff44ff6e975387006dc5bdb613757961/Executions" \
+            --data-urlencode "To=${{ secrets.twilio_number }} \
+            --data-urlencode "From=${{ secrets.proxy_number }} \
+            -u "${{ secrets.twilio_sid }}:${{ secrets.twilio_auth_token }}" \
+            -d "${payload}"
